---
- name: Install python-ldap for Ansible
  become: yes
  apt:
    name: python-ldap
    state: present

- name: Create ldap entry for gerrit admin account
  become: yes
  ldap_entry:
    server_uri: ldap://
    bind_dn: cn=admin,dc=example,dc=org
    bind_pw: secret
    state: present
    dn: cn=gerritadmin,dc=example,dc=org
    objectClass: inetOrgPerson
    attributes:
      uid: "{{ gerrit.admin.username }}"
      userPassword: "{{ gerrit.admin.password }}"
      mail: "{{ gerrit.admin.email }}"
      givenName: Gerrit
      sn: Admin
      cn: gerritadmin

- name: Read ssh key for manual usage.
  shell: cat ~/.ssh/id_rsa.pub
  register: user_ssh_key

- name: Add ssh key to gerritadmin at http://10.10.10.5:8080/#/settings/ssh-keys
  debug:
    msg: {{ user_ssh_key.stdout }}

- pause:
    echo: no
    prompt: Press enter when done to continue.
