---
- name: Set gerrit home
  set_fact:
    gerrit_home: /home/vagrant/gerrit

- name: Create directories for gerrit
  file:
    path: "{{ gerrit_home }}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - etc
    - git
    - db
    - index
    - cache
    - postgres
    - ldap/var
    - ldap/etc

- name: Copy Gerrit configuration
  copy:
    src: "{{ item }}"
    dest: "{{ gerrit_home }}/etc/{{ item }}"
  with_items:
    - gerrit.config
    - secure.config

- name: Generate Gerrit host key
  shell: "ssh-keygen -q -t rsa -f {{ gerrit_home }}/etc/ssh_host_key -N ''"

- name: Permission debug
  become: true
  file:
    path: "{{ gerrit_home }}"
    mode: u=rwX,g=rwX,o=rwX
    recurse: true

- name: Copy gerrit-compose.yaml file
  copy:
    src: gerrit-compose.yaml
    dest: "{{ gerrit_home }}/docker-compose.yaml"

- name: Run postgres container for gerrit
  become: yes
  shell: |
    set -e
    set -x
    docker-compose up -d postgres
  args:
    executable: /bin/bash
    chdir: "{{ gerrit_home }}"

- name: Wait until postgres comes up (naive)
  pause:
    seconds: 10

- name: Initialize Gerrit container
  become: yes
  shell: |
    set -e
    set -x
    docker-compose up gerrit
  args:
    executable: /bin/bash
    chdir: "{{ gerrit_home }}"

- name: Remove init entrypoint for Gerrit
  lineinfile:
    path: "{{ gerrit_home }}/docker-compose.yaml"
    state: absent
    regexp: "entrypoint"

- name: Run gerrit container in daemon mode
  become: yes
  shell: |
    set -e
    set -x
    docker-compose up -d
  args:
    executable: /bin/bash
    chdir: "{{ gerrit_home }}"
